### PR TITLE
Adds handling for Django SubfieldBase deprecation

### PR DESCRIPTION
**Pull request by arecker**
Handles upcoming deprecation for SubfieldBase.

Inspired by [this](https://github.com/pennersr/django-allauth/pull/1118/files) merge request.

### CODE REVIEW

**Comment by arecker** [comment]
Fixing this...

**Comment by arecker** [comment]
Failing on the forms stuff?  Suggestions?

**Comment by jaddison** [comment]
Is there something in SubfieldBase that allows those form tests to pass? I too was trying to create a pull request for this and ran into the same issues.

**Comment by mfogel** [comment]
I think the failing forms tests came from a change in django's behavior as noted [here](https://docs.djangoproject.com/en/1.9/releases/1.8/#subfieldbase). "Note that the new approach does not call the to_python() method on assignment..." The tests were assuming `to_python()` would be called on assignment, and thus a validation error thrown. I've changed around those tests so they now explicitly call `full_clean()` to trigger the validation errors.

I should have cherry-picked this commit over and then adjusted things from there - apologies, @arecker I didn't think to do it. Appreciate you writing this up, it was helpful.

This functionality will be included in the next release pushed to pypi, which I will get out there later today.

**Comment by arecker** [comment]
No worries.  Thanks for addressing.

**Pull request closed without merging**
