### PR TITLE
Add django rest framework support

### PR DESCRIPTION
**Pull request by starryrbs**
Add django rest framework field TimeZoneField, please review!

### CODE REVIEW

**Comment by mfogel** [comment]
Thank you for the PR @starryrbs !

Could I ask two things
- adding django rest framework to setup.py, using `extras_require` ? 
- tests. In the `tests/` dir there is a django project, it should be possible to add django rest-framework to that project and then add one or more basic tests that ensure this new rest-framework field does what it's supposed to do

**Comment by starryrbs** [comment]
Thank you for your review @mfogel !
 I've added tests and add extras_require, please review again.

> Thank you for the PR @starryrbs !
> 
> Could I ask two things
> 
> * adding django rest framework to setup.py, using `extras_require` ?
> * tests. In the `tests/` dir there is a django project, it should be possible to add django rest-framework to that project and then add one or more basic tests that ensure this new rest-framework field does what it's supposed to do

Thank you for your review @mfogel !
 I've added tests and add extras_require, please review again.

**Comment by mfogel** [comment]
@starryrbs I merged this in as part of de581ea. I did a few tweaks before merging in, the one that will probably most affect you is I adjusted the import path. Users of this package will do `from timezone_field import TimeZoneSerializerField` to import the serializer field now.

Please try it out in your project(s) when you get a chance and let me know if anything comes up. I don't use django nor django restframework on a daily basis anymore so apologies in advance if I missed something.

I'm planning to release a new version of this package within a few weeks which will contain this feature. Thanks for your contribution!

**Comment by starryrbs** [comment]
Okay, thank you for adding this feature!

**Pull request closed without merging**
